### ISSUE TITLE
"no jQuery" but has it as a dependency

### ISSUE THREAD

**Issue by irahopkinson** [fromkeith/ng-intl-tel-mini#1]
https://github.com/fromkeith/ng-intl-tel-mini/blob/a64ad8016ff3357cc25d79c4104df18a9aefd999/package.json#L15

This project looks good. However it claims to have "no jQuery" but it is still a dependency of this project, i.e. npm will install jQuery. How does that work?

**Comment by fromkeith** [comment]
Mmm. good question. I'll have to take a look at that.

**Comment by fromkeith** [comment]
Removed. I think it was just a legacy import from when I started building this package.
Thanks for pointing it out!
